general:
  udp-host: udp.apiv3.errplane.com
  http-host: w.apiv3.errplane.com

  api-key: 962cdc9b-15e7-4b25-9a0d-24a45cfc6bc1 # your api key (Settings/Organization)
  app-key: ac361914                             # your app key (Settings/Applications)
  environment: staging                          # your environment (Settings/Applications)

  sleep: 10s                                    # frequency of sampling (accepted suffix, s for seconds, m for minutes and h for hours)
  proxy:                                        # proxy to use when making http requests (e.g. https://201.20.177.185:8080/)
