general:
  udp-host: udp.apiv3.errplane.com:8126
  http-host: w.apiv3.errplane.com

  api-key:      # your api key (Settings/Organization)
  app-key:      # your app key (Settings/Applications)
  environment:  # your environment (Settings/Applications)

  sleep: 10s                                    # frequency of sampling (accepted suffix, s for seconds, m for minutes and h for hours)
  proxy:                                        # proxy to use when making http requests (e.g. https://201.20.177.185:8080/)
  log-file: /data/errplane-agent/shared/log.txt # the log file of the agent
  log-level: debug                              # debug, info, warn, error
  top-n-processes: 10                           # For processes stats the agent will report the top n processes (by memory and cpu usage)
